### ISSUE TITLE
Please Update dll

### ISSUE THREAD

**Issue by zerosherd** [matanki-saito/CK2dll#106]
The main application has updated, please support it.THX

**Comment by matanki-saito** [comment]
Hi, is your version 3.1.1 ? 
If you have autoupdate disabled, please enable.
Or, please overwrite the following files with the existing files.
https://github.com/matanki-saito/CK2dll/releases/download/Build-20190516.1/steam_CK2_2.8.X-3.0.X_mbdll_build_20190516.1.zip

**Comment by matanki-saito** [comment]
However, there is an update (3.2) of the body tomorrow.
https://forum.paradoxplaza.com/forum/index.php?threads/ck2-dev-diary-128-the-iron-century-finale.1180582/
I need to respond to it.
This will take some time.
Thx.

**Comment by matanki-saito** [comment]
done
