### ISSUE TITLE
I made a patch that allow achievement with dynamic patch

### ISSUE THREAD

**Issue by Ai-Himmel** [matanki-saito/CK2dll#111]
https://github.com/Ai-Himmel/bypass_ck2_checksum

**Comment by matanki-saito** [comment]
That's interesting 👍

**Comment by matanki-saito** [comment]
I find same pattern at v3.3.2.

![image](https://user-images.githubusercontent.com/35730970/75616810-63295b00-5b99-11ea-9de2-5060db8b5c85.png)

0F 94 C1 88 4F 63 48 8B  46 30
 -> B0 01 90 88 4F 63 48 8B  46 30
