### ISSUE TITLE
Unexpected Line Breaks

### ISSUE THREAD

**Issue by Unknown-Tokyo** [matanki-saito/CK2dll#114]
Version 3.3
Sometimes the desc starts a new line without '\n'. It gets normal lines and a single (2 bytes) character (or a word in single byte language?) per line alternating show.

Most serious situation like that:
![QQ截图20200130161313](https://user-images.githubusercontent.com/41478553/73431458-6e5f5000-437b-11ea-8c28-2825bb3943c9.jpg)

**Comment by matanki-saito** [comment]
Yes, I am aware of the problem.
Some code has not yet been ported from 3.2 to 3.3.
I think that problem can be fixed by March

thx

**Comment by matanki-saito** [comment]
Fixed the problem. please try new release 
https://github.com/matanki-saito/CK2dll/releases/tag/Build-20200208.1
