### ISSUE TITLE
Cannot start game when dllautoupdater fails

### ISSUE THREAD

**Issue by qinq-net** [matanki-saito/CK2dll#117]
Sometimes when network is not good, dllautoupdater may fail, and the game will refuse to start, even if the DLL is newest.

**Comment by matanki-saito** [comment]
thx,  I will review my code

**Comment by matanki-saito** [comment]
Now, if communication cannot be established within 40 seconds, the game is shut down (exit), but I will try to give only an alert dialog without shutting down.
I'm also going to be able to enable or disable in the ini
