### ISSUE TITLE
there are some bugs in 3.3.3 verson ck2dll

### ISSUE THREAD

**Issue by stl200101** [matanki-saito/CK2dll#129]
i think the most important problem is that when i want to save or load game,the game will crash very soon.the second bug is that when there is no detail windows in the game ,i can't use esc to call the menu.

**Comment by matanki-saito** [comment]
Let me confirm

**Comment by matanki-saito** [comment]
Done !
 - https://github.com/matanki-saito/CK2dll/releases/tag/7
