### ISSUE TITLE
The key of ESC doesn't work properly

### ISSUE THREAD

**Issue by toylsc** [matanki-saito/CK2dll#131]
I have noticed that someone has mentioned the same bug in issue #129 and the bug has been considered to be solved in the latest DLL. However the problem still exists. The details of the bug is as following:

Generally, when pressing ESC, any opened window should be closed if there exists one. Otherwise, the exist menu should appear. Also, when the exist menu is opened, pressing ESC again would close the exit menu.

With the bug, when there is no opened window (e.g. a character window or a province window), pressing ESC does nothing. And when any window is opened, pressing ESC would close the opened window and the exit menu appears immediately. Also, pressing ESC again would not close the exit menu.

This bug makes it inconvenient when a player wants to open or close the exist menu with ESC.

**Comment by matanki-saito** [comment]
Let me confirm

**Comment by matanki-saito** [comment]
Done ! https://github.com/matanki-saito/CK2dll/releases/tag/8

**Comment by toylsc** [comment]
Great! お疲れ様です!

**Comment by flyonbed999** [comment]
THX!
