### ISSUE TITLE
i think the new version dll also have some  bugs

### ISSUE THREAD

**Issue by stl200101** [matanki-saito/CK2dll#135]
first, thankyou for your reply and your work, i have updated the dll to the Release 8,but when i start game and want to load old save,the game has  crashed.my old save was base on the  Release 7.

**Comment by matanki-saito** [comment]
hmm Can I have your saved data? 
And tell me all the MOD you have enabled.

**Comment by stl200101** [comment]
i am sorry that i can only tell you my old save was base on hip mod beacause i deleted my old save last night

**Comment by matanki-saito** [comment]
Okay.
Please let me know if it occurs again
