### ISSUE TITLE
character skills display issue

### ISSUE THREAD

**Issue by hcccccz** [matanki-saito/CK2dll#137]
![屏幕截图(21)](https://user-images.githubusercontent.com/40889071/84253850-49b37b80-aac5-11ea-855a-530f277a1908.png)

if chinese mod added, the issue becomes more obvious
![屏幕截图(18)](https://user-images.githubusercontent.com/40889071/84253887-5506a700-aac5-11ea-8089-51d377349994.png)

**Comment by matanki-saito** [comment]
Sorry , I tried to fix the line break issue for 3.3. But it didn't work. 
Please fix the domestic_dynastic.gui file.
 Japanese issue : https://github.com/matanki-saito/CK2JPModCore/issues/15
 Fix code: https://github.com/matanki-saito/CK2JPModCore/commit/71c183bcc6271e9d22ba804af4bb0f801898864e

**Comment by hcccccz** [comment]
Thank you for reply, can I change maxWidth to larger value ? eg 29

**Comment by matanki-saito** [comment]
Yes.
If you change the maxWidth during the game and command `reload domestic_dynastic.gui` on the console, the settings will reload. Adjust it a little at a time.

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/84344511-f38a2980-abe5-11ea-8f0d-62a80792152b.png)
