### ISSUE TITLE
bug with 3.3.3

### ISSUE THREAD

**Issue by kreisler1026** [matanki-saito/CK2dll#138]
I can't type or using any key except ESC and F1-F12
can't press spacebar to past the time or anything
sorry about my broken english

**Comment by matanki-saito** [comment]
Let me confirm

**Comment by kreisler1026** [comment]
Thx

**Comment by stl200101** [comment]
The new version can work.

**Comment by matanki-saito** [comment]
@kreisler1026 
The Release zip contains SDL2.dll.
 -  https://github.com/matanki-saito/CK2dll/releases/tag/9

Please overwrite the file.
`C:\Program Files (x86)\Steam\steamapps\common\Crusader Kings II\SDL2.dll`

thx
