### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by kreisler1026** [matanki-saito/CK2dll#143]
the launcher will crash after I used this patch
sry about my broken english

**Comment by matanki-saito** [comment]
@kreisler1026 
 Please check followings

## When did the game crash?

- After pressing the Play button on the launcher
- Loading screen
- game playing
- event popup
- save the game

## Windows version

- 10
- other (please tell me the your version)

## Platform version

- steam
- other (sorry. This patch is not supported other platform)

## Game version

- 3.3.5.1　
- other (please tell me the your version)

## Using the installer ?

Installer is [here](https://github.com/matanki-saito/SimpleInstaller)

- yes
- no

## What language mods have you used?

- Japanese
- Chinese
- Korean
- other

## Do you have anti-virus software installed?

- yes
  - Windows Defender
  - other(please tell me the using software name)
- no

**Comment by kreisler1026** [comment]
Launcher will crash when I just open it

**Comment by kreisler1026** [comment]
Nvm,I solve the problem
I'm a dumb,all I need to do is just delete all my old save file
