### ISSUE TITLE
launch failure

### ISSUE THREAD

**Issue by SZooo** [matanki-saito/CK2dll#144]
game version: 3.3.4

unzip releases 14 into the game directory and the game doesn't launch, then i restore the original file to launch properly

**Comment by matanki-saito** [comment]
@SZooo 
 Please check followings

## When did the game crash?

- After pressing the Play button on the launcher
- Loading screen
- game playing
- event popup
- save the game

## Windows version

- 10
- other (please tell me the your version)

## Platform version

- steam
- other (sorry. This patch is not supported other platform)

## Using the installer ?

Installer is [here](https://github.com/matanki-saito/SimpleInstaller)

- yes
- no

## What language mods have you used?

- Japanese
- Chinese
- Korean
- other

## Using  other mods ?

 - yes  (please tell me  mods)
 - no

## Do you have anti-virus software installed?

- yes
  - Windows Defender
  - other(please tell me the using software name)
- no

**Comment by SZooo** [comment]
I found the reason, I need to delete the old archive file containing Chinese characters before it can be opened properly

> @SZooo Please check followings
> ## When did the game crash?
> 
>     * After pressing the Play button on the launcher
> 
>     * Loading screen
> 
>     * game playing
> 
>     * event popup
> 
>     * save the game
> 
> 
> ## Windows version
> 
>     * 10
> 
>     * other (please tell me the your version)
> 
> 
> ## Platform version
> 
>     * steam
> 
>     * other (sorry. This patch is not supported other platform)
> 
> 
> ## Using the installer ?
> 
> Installer is [here](https://github.com/matanki-saito/SimpleInstaller)
> 
>     * yes
> 
>     * no
> 
> 
> ## What language mods have you used?
> 
>     * Japanese
> 
>     * Chinese
> 
>     * Korean
> 
>     * other
> 
> 
> ## Using other mods ?
> 
>     * yes  (please tell me  mods)
> 
>     * no
> 
> 
> ## Do you have anti-virus software installed?
> 
>     * yes
>       
>       * Windows Defender
>       * other(please tell me the using software name)
> 
>     * no


**I found the reason, I need to delete the old archive file containing Chinese characters before it can be opened properly**

**Comment by LianJ333** [comment]
这是来自连泽全QQ邮箱的自动回复邮件。您好，您的邮件我已经收到。连泽全
