### ISSUE TITLE
Truncated long province name

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/CK2dll#40]
問題：
州の名前が長いと、末尾の文字が消滅する場合がある。
これは単なる表示上の問題ではなく、州の名前そのものが変更される。

再現性：
常に

再現手順：
1. 1066年のカスティーリャ王サンチョで開始する。
2. イベリア半島北岸にある「アストゥリアス・デ・サンティリャーナ」という州をクリックする。
3. クリックした瞬間、マップ上の州の名前が短くなる。

＊隣にあるレオン領アストゥリアス・デ・オビエドでも同じ現象が起きると思われます。

原因：
EU4dllのIssue #68に酷似しているので、同様の原因である可能性が高い。
ただし、こちらは州ウインドウにキャレットが表示されない。

解決策：
EU4dllのIssue #68と同じ解決策が有効だと思われる。

参考画像：
画像ではフォントを変更していますが、日本語化MOD単独でも再現することを確認しています。

クリック前
![ck2 1](https://user-images.githubusercontent.com/42687608/47981629-f79fbc80-e10f-11e8-8182-b95abb28cfaa.jpg)

クリック後
![ck2 2](https://user-images.githubusercontent.com/42687608/47981639-04bcab80-e110-11e8-86bd-8246fd72668c.jpg)

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
ver3ではこの問題はなぜだか発生しませんでした

**Comment by matanki-saito** [comment]
はみ出したら改行できたと思ったのですが、とりあえず下記で修正完了とします。
![image](https://user-images.githubusercontent.com/35730970/48660724-03916400-eaaa-11e8-9ae7-465beb382217.png)
![image](https://user-images.githubusercontent.com/35730970/48660726-0be99f00-eaaa-11e8-9426-c4bc84f930e8.png)

**Comment by matanki-saito** [comment]
下記を押せなくなることがわかったためreopenしました
![image](https://user-images.githubusercontent.com/35730970/48661400-7b648c00-eab4-11e8-91d5-66ef7696b1e5.png)

**Comment by matanki-saito** [comment]
下記の記述は非常に頼りになる
https://simulationian.com/2017/04/ck2-dd20170424/

**Comment by matanki-saito** [comment]
consoleに「guibounds 」と入れるとIDが表示される。はえーすっごい。
![image](https://user-images.githubusercontent.com/35730970/48664884-1bd4a380-eae9-11e8-9eb1-3c28e0fcbf11.png)

**Comment by matanki-saito** [comment]
上から下に配置されていくっぽいので、記述を下に持ってきた。
![2018-11-18_04h20_26](https://user-images.githubusercontent.com/35730970/48665106-5ab82880-eaec-11e8-843b-77a5dfe57457.png)
![2018-11-18_04h40_47](https://user-images.githubusercontent.com/35730970/48665110-5e4baf80-eaec-11e8-88b8-f4629c5a9bb5.png)

**Comment by matanki-saito** [comment]
大丈夫そうなのでClose。次回更新に含まれる予定
