### ISSUE TITLE
Missing ordinal number of war

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/CK2dll#41]
問題：
戦争名に含まれる「第〜次」の「〜」部分に入るべき数字が消えている。

再現性：
常に

再現手順：
1. 1066年の征服王ウィリアム（カスタムではない方）で開始する。
2. 適当に時間を進める。
3. 大抵フランスと神聖ローマが戦争をはじめる。
4. 画面右下の顔（戦争相手のリーダー）をクリックして戦況ウインドウを開く。
5. ウインドウ上部の戦争名を確認する。

再現環境：
1. CK2のバージョンは2.8.3.3を使用。
2. CK2dllはdev_steam_CK2_2.8_mbdll_build_20181029.1.zipを使用。
3. 日本語化MOD以外のMODおよびDLCは一切導入していない。

原因：
不明

解決策：
不明

参考画像：
![ck2](https://user-images.githubusercontent.com/42687608/48297650-15469a80-e4f1-11e8-80cf-abc2aae67fce.png)

**Comment by matanki-saito** [comment]
ﾔﾙｿﾞ!!Σс(ﾟДﾟс

**Comment by matanki-saito** [comment]
$ORDER$
![image](https://user-images.githubusercontent.com/35730970/48629632-801a3900-e9fd-11e8-9a20-805df96e3b8a.png)

**Comment by matanki-saito** [comment]
英語だとこんな感じだった
![image](https://user-images.githubusercontent.com/35730970/48630526-d4beb380-e9ff-11e8-8624-9f76872f767b.png)

**Comment by matanki-saito** [comment]
つまり、英語の場合は頭にORDERがついているため、消えても不自然に見えない

**Comment by matanki-saito** [comment]
数はそれほどでもない
![image](https://user-images.githubusercontent.com/35730970/48630988-e8b6e500-ea00-11e8-8ead-a68733f12c02.png)

**Comment by matanki-saito** [comment]
この上の方にFIRST_ADJが存在する
![image](https://user-images.githubusercontent.com/35730970/48631352-b063d680-ea01-11e8-84c3-57975597d85a.png)

**Comment by matanki-saito** [comment]
うむーーーわからん
英語だと 2ndのようになるのかな？
https://www.reddit.com/r/CrusaderKings/comments/4oq6se/help_warscore_stuck_at_95_why/
日本語だと2次のようになるのかな？
https://twitter.com/nepi_per/status/1058694555325804545

そして何故か翻訳されていると…

**Comment by matanki-saito** [comment]
んーこれかなあ
![image](https://user-images.githubusercontent.com/35730970/48639764-ec099b00-ea17-11e8-9147-97ff71476d12.png)

**Comment by matanki-saito** [comment]
とりあえず$ORDER$の部分にあった「第」と「次」を削除しておきました
