### ISSUE TITLE
Larger map text

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/CK2dll#47]
問題：
マップ上の文字のサイズが以前のバージョンより大きくなる。

再現性：
常に

再現手順：
1. ゲームを起動する
2. カスタムゲーム（1066年）を選択する
3. 直後に表示されるマップを比較する（特にフランスとビザンツの文字に注目）

原因：
不明
バニラおよび日本語化mod標準のフォントでは発生しないことから、フォント側に原因がある可能性が高い。

解決策：
不明
フォント生成時のサイズを60ptに揃えたり、思い切って20ptにしたりしたが、結果は変わらなかった。

参考画像：

明朝体フォント（ver2.8.3.4）
![min 2 8 3 4](https://user-images.githubusercontent.com/42687608/48658089-4c7ff300-ea7f-11e8-8fae-3c7e5c2a26bf.jpg)

明朝体フォント（ver3.0）
![min 3 0](https://user-images.githubusercontent.com/42687608/48658092-57d31e80-ea7f-11e8-9b04-5ec1cd17b44b.jpg)

刻明朝フォント（ver2.8.3.4）
![koku 2 8 3 4](https://user-images.githubusercontent.com/42687608/48658102-6d484880-ea7f-11e8-8f39-b943228050bf.jpg)

刻明朝フォント（ver3.0）
![koku 3 0](https://user-images.githubusercontent.com/42687608/48658105-776a4700-ea7f-11e8-84f9-871432b7604e.jpg)

日本語化mod標準フォント（ver2.8.3.4）
![jpn 2 8 3 4](https://user-images.githubusercontent.com/42687608/48658118-a1bc0480-ea7f-11e8-93a9-21d6ac626a2b.jpg)

日本語化mod標準フォント（ver3.0）
![jpn 3 0](https://user-images.githubusercontent.com/42687608/48658121-a5e82200-ea7f-11e8-8084-4c4e68ad9a5f.jpg)

バニラ（ver2.8.3.4）
![eng 2 8 3 4](https://user-images.githubusercontent.com/42687608/48658127-ab456c80-ea7f-11e8-845d-da2ce738d4d6.jpg)

バニラ（ver3.0）
![eng 3 0](https://user-images.githubusercontent.com/42687608/48658128-af718a00-ea7f-11e8-8bb5-1fc216b75268.jpg)

**Comment by matanki-saito** [comment]
ふーむ

**Comment by matanki-saito** [comment]
あ～～～バグっていたかもしれない

**Comment by matanki-saito** [comment]
しかし直らない(´・ω:;.:...

**Comment by matanki-saito** [comment]
localisationを抜いて見ました。英語だけでも大きくなるようです。もしかすると仕様変更があったのかも…
![image](https://user-images.githubusercontent.com/35730970/48676393-c14f4c00-eba9-11e8-8028-facb538a6b2d.png)

**Comment by matanki-saito** [comment]
仕様とさせてください。
