### ISSUE TITLE
Crash just after loading finished

### ISSUE THREAD

**Issue by bruceCzK** [matanki-saito/CK2dll#51]
I'm using the latest patch on 3.0, and when loading finished, the game crashed.

Here's the log and dump. I think it contains all the necessary information including the hardware.

[debug.zip](https://github.com/matanki-saito/CK2dll/files/2591924/debug.zip)

**Comment by matanki-saito** [comment]
hmm, I will check it

**Comment by bruceCzK** [comment]
Sorry for the trouble. I've solved the problem. 
It's the `fonts.gfx`.
Dev has changed the font setting file. I was using the old ones.
