### ISSUE TITLE
Version alert not showing current version and supported versions

### ISSUE THREAD

**Issue by bruceCzK** [matanki-saito/CK2dll#65]
https://github.com/matanki-saito/CK2dll/blob/236c5649368f42ba1ad4a629d61aee5a811caac6/Plugin/dllmain.cpp#L94

Message like 'Your current version is 3.0.1.1 is not supported by now. The latest supprot version is 3.0.1, please rollback your main exe. blabla' would be more friendly to users. 
Thanks.

**Comment by matanki-saito** [comment]
Yes, I confirmed that it does not work with 3.0.1.1 (open beta).
I will change the message.
thx

**Comment by bruceCzK** [comment]
Thanks.
