### ISSUE TITLE
3.0.1.1 crash down

### ISSUE THREAD

**Issue by hbtx99099** [matanki-saito/CK2dll#74]
ck2 v3.0.1.1B will crash down when it run few days in the game with any location language mod…thanks…

**Comment by matanki-saito** [comment]
ok, i will check it

**Comment by hbtx99099** [comment]
ありがとうございます。

☆ (ゝω・)v <notifications@github.com> 于 2019年1月13日周日 21:12写道：

**Comment by matanki-saito** [comment]
@hbtx99099 san

Four days ago, I have released a new DLL supporting 3.0.1.1B.
- https://github.com/matanki-saito/CK2dll/releases/tag/Build-20190109.2

Please try using it.

----
A) 
If you get the following alert when you start the game,

![image](https://user-images.githubusercontent.com/35730970/51086150-2c6e6680-1786-11e9-808c-f6086f077e11.png)

please delete "plugins/autoupdate.bat".

![image](https://user-images.githubusercontent.com/35730970/51086173-6b042100-1786-11e9-8a5b-34a40e7f2dd6.png)

----
B)
If you crash during the game, please let me know the details. And please give me your save file.

thx.

**Comment by matanki-saito** [comment]
I found a crashed code.

https://github.com/matanki-saito/CK2dll/blob/9735dcdaadb122730651bacd1f2abbf3c792eabe/Plugin/NickNameFix.cpp

I will fix it.

thx.

**Comment by hbtx99099** [comment]
I am very sorry, I have undergone an surgery today and can't report details
of the problems which I found. In short, thank you for everything you have
done.


☆ (ゝω・)v <notifications@github.com> 于 2019年1月15日周二 00:10写道：
