### ISSUE TITLE
Font render error when UI scale is larger than 1

### ISSUE THREAD

**Issue by bruceCzK** [matanki-saito/CK2dll#77]
The messsage on top right corner is not showing. And the issue is the same in some other places.

![tim 20190216195339](https://user-images.githubusercontent.com/8399711/52899408-b6499d80-3224-11e9-958a-147407264fe0.png)

**Comment by matanki-saito** [comment]
hmm
I have never tried scaling UI. I will try.

**Comment by matanki-saito** [comment]
It may be text-overflow（...）issue.
Recently, It was fixed in EU4dll.
- https://github.com/matanki-saito/EU4dll/issues/99
- https://github.com/matanki-saito/EU4dll/issues/102

**Comment by matanki-saito** [comment]
memo
![image](https://user-images.githubusercontent.com/35730970/54376012-7233a680-46c5-11e9-92d1-ed5284402f69.png)

**Comment by matanki-saito** [comment]
memo
![image](https://user-images.githubusercontent.com/35730970/54376192-e0786900-46c5-11e9-9108-dcbb3d7ea59b.png)

**Comment by matanki-saito** [comment]
memo
I found that Unk4 fixed "..." logic.
https://github.com/matanki-saito/CK2dll/blob/master/Plugin/Unk4.cpp

**Comment by matanki-saito** [comment]
I added some fixes to the code in #83 
1) When the text overflows, the text is correctly replaced by 3 dot (...)
2) Fixed the code to get the width of the character in font.
3) Fixed version error dialog text.
4) Change code encoding to utf-8.

And, when UI scale is larger than 1,  maybe need to set "fontname_gui_scaled" in fonts.gfx.
https://github.com/matanki-saito/CK2JPModCore/blob/b1be8215bbab5910ccd0efbbf0c2cd811853dae7/resource/interface/fonts.gfx#L108

thx

**Comment by bruceCzK** [comment]
Thank you for the good work. For the 4th change in the list, is it means we don't need to do the special escape to csv files?

**Comment by matanki-saito** [comment]
No, it is necessary.
I changed the program code (* .cpp, *.hpp) from shift-JIS encoding to UTF-8 encoding.
It was necessary for the error dialog text.

**Comment by matanki-saito** [comment]
And you can try the development version dll.
If you have enabled automatic updating, please overwrite the bat file on "C:\Program Files (x86)\Steam\steamapps\common\Crusader Kings II\plugins\autoupdate.bat".

[autoupdate.zip](https://github.com/matanki-saito/CK2dll/files/2974753/autoupdate.zip)

or download dll ( https://d3mq2c18xv0s3o.cloudfront.net/api/v1/distribution/139275487/%exeMD5%?dll_md5=%pluginMD5%&phase=dev )

thank you

**Comment by bruceCzK** [comment]
OK. Got it.
