### ISSUE TITLE
Is there any plan porting to SteamOS/Linux?

### ISSUE THREAD

**Issue by qinq-net** [matanki-saito/CK2dll#85]
Your README only mentioned no plan for macOS. So does any plan for SteamOS/Linux exist?

**Comment by matanki-saito** [comment]
Sorry, I don't have this plan.
because I  have no knowledge of Linux...

**Comment by matanki-saito** [comment]
I made an issue to investigate.
https://github.com/matanki-saito/CK2dll/issues/86

but I do not know if I can.It may take a very long time
